### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by 60fpshacksrock** [emoose/xbox-winfsp#15]
Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'Fsp.Interop.Api' threw an exception. ---> System.TypeLoadException: incorrect
 dll version (need 1.6, have 2.0)
   at Fsp.Interop.Api.CheckVersion()
   at Fsp.Interop.Api..cctor()
   --- End of inner exception stack trace ---
   at Fsp.Service..ctor(String ServiceName)
   at XboxWinFsp.Program.Main(String[] args)

**Comment by superkoira** [comment]
you gotta install older version of winfsp. Version 1.6.
